### ISSUE TITLE
Feature request: Add com.uber.autodispose.XXXSubscribeProxy to analyse

### ISSUE THREAD

**Issue by ultraon** [vanniktech/lint-rules#238]
It would be great to add classes from Uber Autodispose library to analyze `subscribe` calls:
- com.uber.autodispose.ObservableSubscribeProxy
- com.uber.autodispose.FlowableSubscribeProxy
- com.uber.autodispose.MaybeSubscribeProxy
- com.uber.autodispose.CompletableSubscribeProxy
- com.uber.autodispose.ParallelSubscribeProxy
- com.uber.autodispose.SingleSubscribeProxy

Autodispose Library: https://github.com/uber/AutoDispose

**Comment by vanniktech** [comment]
Sure. Feel free to submit a PR for that.

**Comment by vanniktech** [comment]
@ultraon any interest in this? Otherwise, I'll close since I'm not using autodispose and I don't think many are consuming these lint rules as it's mostly used for getting started when writing your own rules.

**Comment by ultraon** [comment]
Ok, you can close it
