### ISSUE TITLE
This code is great.

### ISSUE THREAD

**Issue by ouyangpeng** [vanniktech/lint-rules#252]
This code is great.
This is exactly what I need reference code.

**Comment by ouyangpeng** [comment]
> This code is great.
This is exactly what I need reference code.

**Comment by vanniktech** [comment]
You're welcome! If you have any questions feel free to ask.

**Comment by ouyangpeng** [comment]
I has wrote the lint custom rules and lint plugin last year, but it base on gradle 2.x，now gradle version is 3.x, and it is not working now, so i must write the new  custom rules and lint plugin base gradle 3.x , using java or kotlin language!

**Comment by ouyangpeng** [comment]
i have learn a lot from your code,thank you ! i have implement my custom lint rules and lint plugin that base on gradle 3.x !  @vanniktech
