### ISSUE TITLE
RxJava2MethodMissingCheckReturnValue on private functions

### ISSUE THREAD

**Issue by tasomaniac** [vanniktech/lint-rules#267]
I found `RxJava2MethodMissingCheckReturnValue` very valuable. Thanks for that. 

But not so much when it comes to private functions. Often times I extract some of the `RxJava` chains just to have better names etc. Then I feel like it is too much to put `CheckReturnValue` everywhere. I would just put them on the public API. 

What is your opinion on this? 

I wonder if it is possible to make lint checks configurable? I guess not atm.

**Comment by vanniktech** [comment]
> What is your opinion on this?

I still put it on private methods. Essentially, that one call to a private method that's not checking for the result value can still ruin everything.

> I wonder if it is possible to make lint checks configurable? I guess not atm.

Only via System variables. There was a thread about this in the Lint Dev group.

**Comment by tasomaniac** [comment]
Would it make sense to split the check for public and private declarations? I know the repo wants to stay opiniated but still just asking. 😊

**Comment by vanniktech** [comment]
I'd rather have a list of modifiers that can be passed via a System variable on which this should be ignored. There's some information on how to do this here - https://groups.google.com/forum/#!topic/lint-dev/hAMZS9kZzgg

**Comment by tasomaniac** [comment]
Let's come up with a system variable name, then. 

What about `lint.rxjava2.methodMissingCheckReturnValue.ignoreMethodAccessModifiers`?

**Comment by vanniktech** [comment]
`com.vanniktech.lintrules.rxjava2.RxJava2MethodMissingCheckReturnValueDetector.ignoreMethodAccessModifiers` - let's just use the fully qualified name? That way it's unique and easily traceable.
