### ISSUE TITLE
Consider removing `AssertjImport` check

### ISSUE THREAD

**Issue by tasomaniac** [vanniktech/lint-rules#268]
`AssertjImport` check may not be necessary anymore since it is pretty common to target Java 8 among Android developers nowadays.

**Comment by vanniktech** [comment]
Even with that I still had problems. Hence I always stuck do the Java6 imports.

**Comment by tasomaniac** [comment]
Interesting, I've not came accross that and I'm using the java8 packages. Anyways, it is easy to disable checks anyways. So it's no problem. Feel free to close the issue then 👍
