### ISSUE TITLE
MatchingViewId lint fix bug

### ISSUE THREAD

**Issue by tasomaniac** [vanniktech/lint-rules#284]
`MatchingViewId` lint fix just replaces the whole id with the `layout` name, instead of prefixing it with the layout name. All ids become the same. 

Example:

Let's say I have `@+id/button` inside `login_fragment.xml`. The id becomes `loginFragment`, but it should become `loginFragmentButton`

**Comment by vanniktech** [comment]
Yes. I'm aware of that. This case is trivial but there are others which aren't that clear.
