### ISSUE TITLE
False Positive on RxJava2MethodMissingCheckReturnValue

### ISSUE THREAD

**Issue by tasomaniac** [vanniktech/lint-rules#286]
Here we have a Kotlin abstract class extending from Android Databinding `BaseObservable` and we are getting a RxJava related warning. Could it be a false positive?

<img width="476" alt="Screenshot_2019-03-29_at_17 23 31" src="https://user-images.githubusercontent.com/763339/55247316-95bf2b00-5247-11e9-8036-37539a8c8c2f.png">

**Comment by vanniktech** [comment]
Yes. Can be.

**Comment by tasomaniac** [comment]
I will create a test case to see what they say

**Comment by tasomaniac** [comment]
Nope! `BaseObservable` is not the reason and is just a coincidence. Notice there are 6 warnings too. 

Warnings come from `MvRxView`. It is an interface and contains 6 functions with `Disposable` return value and they are not annotation with CheckReturnValue.
