### ISSUE TITLE
WrongAnnotationError problem with Custom annotations

### ISSUE THREAD

**Issue by tasomaniac** [vanniktech/lint-rules#289]
When custom annotations are present, `WrongAnnotationError` expects custom ones to be at the end. It can be seen here that it expects Inject to be before any custom annotation: https://github.com/vanniktech/lint-rules/blob/master/lint-rules-android-lint/src/test/java/com/vanniktech/lintrules/android/AnnotationOrderDetectorTest.kt#L349

This particular instance works well. But it is a problem when used with Kotlin. Kotlin puts Nullable, NonNull annotations automatically. That means when used together with custom annotation, it will always result in an error. 

The following instance for example: 
```
@BindingAdapter("toolbarSubtitle")
fun Toolbar.setToolbarSubtitle(text: String?) {
    text?.let {
        subtitle = text
    }
}
```

There is no way to fix the given warning since there is only a single annotation.

I was gonna open a PR by just ignoring custom annotations. It is a small change in the code and fixes the issue. But then the given test above was breaking.

What do you think? Should I do that?

**Comment by vanniktech** [comment]
Can't we somehow do something smart so custom annotations are always at the end? Like ignore NonNull/Nullable which are being added automatically from Kotlin.

**Comment by tasomaniac** [comment]
I can have another look. Can you also have a look at the PR and my changes?

I can maybe do that for annotations from jetbrains package. I'm not sure if it's easy to check Null annotations plus checking if they're Kotlin. Can you help me on that?

**Comment by vanniktech** [comment]
I did. Didn't I?

**Comment by vanniktech** [comment]
I think they are using the jetbrains annotations which are NotNull so we can just exclude them.
