### ISSUE TITLE
Some rules not working in Android studio

### ISSUE THREAD

**Issue by mf-social** [vanniktech/lint-rules#307]
Hi,

I just discovered this library and am sure it's something I'm doing wrong, but I cannot work out what.

Having installed the library and run a lint check it indeed found lots of issues that I dutifully went through and corrected.

However it is not picking up these two (maybe more, these are the only ones I noticed because I knew I had some of these pending correction)...

 - RawDimen - defining dimension sizes in sp or dp rather than calling @dimen/something is not picked up
 - HardCodedText - whilst not specific to this library, since adding the library the linter no longer picks up text="Hello World!" as a warning that @string/something should be used, which it used to do by default (and is still showing as enabled in the Android Studio linter settings)

Any help appreciated, if you need any more information form me please let me know.

Thanks

**Comment by vanniktech** [comment]
> RawDimen

That's probably since it looks at multiple files and AS does not support it. Feel free to report over at Google.

> HardCodedText

Isn't that the one coming from Google?

**Comment by mf-social** [comment]
> That's probably since it looks at multiple files and AS does not support it. Feel free to report over at Google.

Be happy to, but where and what would I report? I feel I'm lacking in the ability to technically describe what I want them to know, and who would want to know it .  Can you expand on the explanation a bit please? 🙂 

> Isn't that the one coming from Google?

Yeah, but since adding this library to my gradle it's stopped working, in spite of still showing as enabled in the AS linter settings.  I actually noticed that first and then the RawDimen issue afterwards.  I was under the impression that they could both co-exist (and appear to with the other lint specs).  Given that the RawDimen and HardcodedText are very similar to each other in function and are both not working since installing this library (and are the only ones standing out as not working) I figured they were linked. 🤷‍♂️

**Comment by vanniktech** [comment]
1. The normal Android tracker with the Lint category. Or maybe ask in the lint dev forum.

2. That sounds weird and like a Lint bug.

**Comment by mf-social** [comment]
OK - I'll keep playing and see if I can get it working locally, and if not I'll take it across to the Android tracker.

Thanks for your time 👍
