### ISSUE TITLE
WrongAnnotationOrder change order for @Override annotation

### ISSUE THREAD

**Issue by 1951FDG** [vanniktech/lint-rules#319]
Hi @vanniktech,

I recently ran all the lints against my project, one of the lints, WrongAnnotationOrder, changes the default order for `@Override`

I recommend a change, to ensure that `@Override` is always first, and not to change the order of `@Override` if it is first

Example (desired order):

```java
@SuppressWarnings("MagicCharacter")
@NonNull
@Override
public String toString() {}
```

**Comment by vanniktech** [comment]
Personally, I prefer having the @Override as close to the method as possible.

**Comment by 1951FDG** [comment]
`Personally, I prefer having the @override as close to the method as possible.
`

Like in the example? That would be exactly what I propose.
