### ISSUE TITLE
Integration of Lint Rules Resulting in NamingPattern Error

### ISSUE THREAD

**Issue by imjosephmj** [vanniktech/lint-rules#455]
We recently integrated lint rules for the test module, and suddenly, we began encountering a NamingPattern lint error.

The convention we adhere to for tests is outlined here: https://kotlinlang.org/docs/coding-conventions.html#names-for-test-methods

Our tests typically resemble the following format:

```
 @Test
 fun `WHEN scenario, THEN should give expected`() { }
```

Here is how the lint error appears:

**_Explanation for issues of type "NamingPattern":
Sometimes, there is more than one reasonable way to convert an English phrase into camel case, especially when acronyms or unconventional constructs like "IPv6" or "iOS" are involved. For example, XML HTTP request becomes XmlHttpRequest. However, XMLHTTPRequest would be incorrect._**

**Comment by vanniktech** [comment]
You could enable that rule in test sources using the `lint.xml` file.

**Comment by imjosephmj** [comment]
I did enable it, but it seems like the rule is not working as expected. I can go with an exclusion in the lint.xml file now as show below.

```
<issue id="NamingPattern" severity="ignore">
        <ignore path="**/test/**/**Test" />
</issue>
```

However, should we perform this check inside the NamingPattern detector? Please correct me if I'm wrong. If this approach is correct, let's ignore the issue ✨

**Comment by vanniktech** [comment]
Yeah, I'd keep it that way.
